// boot.js — boots the real 317 web client (TeaVM bundle ./webclient.js).
//
// Contract with the Java side (com.ardor.web): before calling start(), this
// script populates two globals, then imports the ES module and calls
// start("game", wsUrl).
//
//   globalThis.__ardorCache = {              // read by WebCacheBootstrap
//     "main_file_cache.dat":  Int8Array,
//     "main_file_cache.idx0": Int8Array, ... "main_file_cache.idx6": Int8Array,
//     // ephemeral pair optional (Java tolerates absence):
//     "main_file_cache.ephemeral.dat": Int8Array,
//     "main_file_cache.ephemeral.idx": Int8Array,
//   }
//
//   globalThis.__ardorSlices = {             // read by WebSliceBootstrap
//     "telos/js5-1.jflat": Int8Array, "cox/main_file_cache.dat2": Int8Array, ...
//   }
//
// The slices carry the cross-cache bundle content (CoX, Gauntlet, Telos, the RS3
// extra maps). Without them the client boots and plays, but every bundle-backed
// NPC is invisible and its arena renders blank — the 317 defs for those NPCs
// deliberately carry no models, because the mesh lives in the slice. The Java
// side writes them into TeaVM's in-memory filesystem so the ordinary
// File-based slice readers find them.

const CANVAS_ID = "game";
const FIXED_W = 765;
const FIXED_H = 503;

// Where the cache is served from. Resolution order:
//   1. ?cache=<url>            — per-visit override (dev / testing)
//   2. window.ARDOR_CACHE_BASE — set by a deploy-time config.js (see dist/)
//   3. ./cache/                — local `nix run .#webclient-poc` symlink
//
// A public static host is NOT one of the defaults on purpose: the Pages repo is
// force-pushed as a single orphan commit holding page assets only, so a deploy
// MUST point this at your own host (with CORS allowing the Pages origin).
// See docs/webclient_deploy.md.
function resolveCacheBase() {
    const fromQuery = new URLSearchParams(location.search).get("cache");
    const base = fromQuery || globalThis.ARDOR_CACHE_BASE || "./cache/";
    return base.endsWith("/") ? base : base + "/";
}

const CACHE_BASE = resolveCacheBase();

// The manifest (generated by scripts/webcache-manifest.sh into the served tree)
// is the single source of truth for what to download and what each file must
// hash to. It replaced a HEAD-derived version stamp on main_file_cache.dat; see
// loadManifest() for what that could not do.
const MANIFEST_FILE = "webcache_manifest.json";

// Fallback when the host serves no manifest — an older deploy. Boots the game
// from the 317 cache alone, with no slices and no integrity checking, and says
// so. Keeping this means upgrading the client does not require the cache host to
// be updated in the same breath.
const FALLBACK_FILES = [
    { path: "main_file_cache.dat", optional: false },
    { path: "main_file_cache.idx0", optional: false },
    { path: "main_file_cache.idx1", optional: false },
    { path: "main_file_cache.idx2", optional: false },
    { path: "main_file_cache.idx3", optional: false },
    { path: "main_file_cache.idx4", optional: false },
    { path: "main_file_cache.idx5", optional: false },
    { path: "main_file_cache.idx6", optional: false },
    { path: "main_file_cache.ephemeral.dat", optional: true },
    { path: "main_file_cache.ephemeral.idx", optional: true },
];

const SLICE_PREFIX = "slices/";

// ── Persistent cache (IndexedDB) ─────────────────────────────────────────────
//
// Without this the client re-downloads ~134MB on EVERY page load: the fetches
// below land in memory only, and the browser's HTTP cache is not a reliable
// backstop for an entity that size (it is eviction-prone, and GitHub Pages
// serves max-age=600). Persisting turns a repeat visit into one manifest fetch.
//
// Records are keyed by manifest path and hold { bytes, size, sha256 } — the
// identity the file had when it was stored. A stored record is reusable when it
// still matches the manifest entry, so a cache update re-fetches only the files
// that actually changed, and a half-written store heals file by file instead of
// throwing everything away.
const DB_NAME = "ardor-webcache";
// v2: per-file { bytes, size, sha256 } records replacing v1's bare blobs +
// single global stamp. onupgradeneeded drops the old stores rather than trying
// to interpret v1 blobs as v2 records.
const DB_VERSION = 2;
const STORE_FILES = "files";

/** Opens the store, or resolves null if IndexedDB is unusable (private mode, disabled). */
function openDb() {
    return new Promise((resolve) => {
        let req;
        try {
            req = indexedDB.open(DB_NAME, DB_VERSION);
        } catch (err) {
            console.warn(`IndexedDB unavailable (${err.message}); cache will not persist.`);
            resolve(null);
            return;
        }
        req.onupgradeneeded = () => {
            const db = req.result;
            // Any pre-v2 content is a different record shape; start clean.
            for (const name of Array.from(db.objectStoreNames)) {
                db.deleteObjectStore(name);
            }
            db.createObjectStore(STORE_FILES);
        };
        req.onsuccess = () => resolve(req.result);
        req.onerror = () => {
            console.warn(`IndexedDB open failed (${req.error}); cache will not persist.`);
            resolve(null);
        };
    });
}

function idbGet(db, store, key) {
    return new Promise((resolve, reject) => {
        const req = db.transaction(store, "readonly").objectStore(store).get(key);
        req.onsuccess = () => resolve(req.result);
        req.onerror = () => reject(req.error);
    });
}

function idbPut(db, store, key, value) {
    return new Promise((resolve, reject) => {
        const tx = db.transaction(store, "readwrite");
        tx.objectStore(store).put(value, key);
        tx.oncomplete = resolve;
        tx.onerror = () => reject(tx.error);
        tx.onabort = () => reject(tx.error);
    });
}

/** Drops stored files the manifest no longer lists (a renamed or retired slice). */
async function pruneUnlisted(db, keep) {
    const keys = await new Promise((resolve, reject) => {
        const req = db.transaction(STORE_FILES, "readonly").objectStore(STORE_FILES).getAllKeys();
        req.onsuccess = () => resolve(req.result);
        req.onerror = () => reject(req.error);
    });
    const stale = keys.filter((k) => !keep.has(k));
    if (stale.length === 0) return;
    await new Promise((resolve, reject) => {
        const tx = db.transaction(STORE_FILES, "readwrite");
        const files = tx.objectStore(STORE_FILES);
        for (const key of stale) files.delete(key);
        tx.oncomplete = resolve;
        tx.onerror = () => reject(tx.error);
        tx.onabort = () => reject(tx.error);
    });
    console.info(`evicted ${stale.length} cache file(s) the manifest no longer lists`);
}

// ── Integrity ────────────────────────────────────────────────────────────────

/**
 * SHA-256 as lowercase hex, or null when the browser has no SubtleCrypto —
 * which is the case on a plain-http origin other than localhost, since
 * crypto.subtle is restricted to secure contexts. Hash checking is therefore
 * best-effort by design: size is always checked, and a missing hash never
 * blocks a boot that would otherwise work.
 */
async function sha256Hex(bytes) {
    if (!globalThis.crypto || !crypto.subtle) return null;
    const digest = await crypto.subtle.digest("SHA-256", bytes);
    return Array.from(new Uint8Array(digest))
        .map((b) => b.toString(16).padStart(2, "0"))
        .join("");
}

/** True when a stored record still satisfies its manifest entry. */
function recordMatches(record, entry) {
    if (!record || !record.bytes) return false;
    if (typeof entry.size === "number" && record.bytes.byteLength !== entry.size) return false;
    // Compare the hash the record was STORED with against the manifest's. This is
    // an identity check, not a re-verification: rehashing 134MB on every visit
    // would cost more than it catches. ?verify=1 forces the full audit.
    if (entry.sha256 && record.sha256 && record.sha256 !== entry.sha256) return false;
    return true;
}

// ── Status / progress UI ─────────────────────────────────────────────────────

const statusEl = document.getElementById("status");
const barEl = document.getElementById("progress-bar");
const barFillEl = document.getElementById("progress-fill");

function setStatus(msg, isError = false) {
    statusEl.textContent = msg;
    statusEl.classList.toggle("error", isError);
    if (isError) console.error(msg);
}

/** Shows the bar at a fraction 0..1, or hides it when given null. */
function setProgress(fraction) {
    if (!barEl) return;
    if (fraction === null) {
        barEl.hidden = true;
        return;
    }
    barEl.hidden = false;
    const pct = Math.max(0, Math.min(1, fraction)) * 100;
    barFillEl.style.width = `${pct.toFixed(1)}%`;
    barEl.setAttribute("aria-valuenow", pct.toFixed(0));
}

function mb(bytes) {
    return (bytes / (1024 * 1024)).toFixed(1);
}

// Same resolution order as the cache base: ?ws= → deploy config → local dev.
//
// A page served over HTTPS (any Pages deploy) CANNOT open a ws:// socket —
// browsers block it as mixed content, and the failure surfaces as an opaque
// connect error, not as anything naming TLS. A public deploy therefore needs a
// wss:// endpoint (terminate TLS in front of the game server) configured via
// window.ARDOR_WS_URL. We fail loudly here rather than let it look like a
// server-down problem.
function resolveWsUrl() {
    const fromQuery = new URLSearchParams(location.search).get("ws");
    const url = fromQuery || globalThis.ARDOR_WS_URL || "ws://127.0.0.1:43599";
    if (location.protocol === "https:" && url.startsWith("ws://")) {
        throw new Error(
            `This page is HTTPS, so the browser will block the insecure ws:// ` +
            `game socket as mixed content. Configure a wss:// endpoint ` +
            `(window.ARDOR_WS_URL in config.js, or ?ws=wss://...).`
        );
    }
    return url;
}

// ── Download ─────────────────────────────────────────────────────────────────

/**
 * Fetches one file, reporting bytes as they arrive rather than only at the end.
 * res.arrayBuffer() would hide a 42MB download behind a single frozen line; the
 * stream reader turns it into a moving bar. Falls back to arrayBuffer() when the
 * response has no readable body stream.
 */
async function fetchCacheFileOnce(entry, onChunk) {
    // no-store, not the default: the recommended host config serves these files
    // `immutable`, which tells the browser never to revalidate. We only reach
    // here when the persisted copy could not serve the file, so the HTTP cache
    // must not answer with the stale bytes `immutable` would otherwise pin. It
    // also stops the browser storing a second ~134MB copy alongside the
    // IndexedDB one — persistence is this module's job, not the HTTP cache's.
    const res = await fetch(CACHE_BASE + entry.path, { cache: "no-store" });
    if (!res.ok) {
        throw new Error(`fetch ${entry.path} → HTTP ${res.status} ${res.statusText}`);
    }
    if (!res.body || !res.body.getReader) {
        const buf = await res.arrayBuffer();
        onChunk(buf.byteLength);
        return new Uint8Array(buf);
    }
    const reader = res.body.getReader();
    const chunks = [];
    let total = 0;
    for (;;) {
        const { done, value } = await reader.read();
        if (done) break;
        chunks.push(value);
        total += value.byteLength;
        onChunk(value.byteLength);
    }
    const out = new Uint8Array(total);
    let at = 0;
    for (const chunk of chunks) {
        out.set(chunk, at);
        at += chunk.byteLength;
    }
    return out;
}

/**
 * fetchCacheFileOnce with retries. A ~134MB first visit spans minutes, and a
 * single transient failure anywhere in it used to abort the whole boot with
 * "Failed to load cache" — a dead page for what a second attempt fixes. Browsers
 * cancel in-flight fetches for reasons that have nothing to do with the file
 * (another tab's navigation, a flaky connection, a sleeping laptop).
 *
 * A retry re-fetches from byte zero, so the bytes the failed attempt already
 * reported are rewound out of the caller's running total first — otherwise the
 * progress bar overcounts and reads past 100%.
 */
async function fetchCacheFile(entry, onChunk) {
    const ATTEMPTS = 3;
    for (let attempt = 1; ; attempt++) {
        let reported = 0;
        try {
            return await fetchCacheFileOnce(entry, (n) => {
                reported += n;
                onChunk(n);
            });
        } catch (err) {
            onChunk(-reported);
            if (attempt >= ATTEMPTS) throw err;
            console.warn(`fetch ${entry.path} failed (attempt ${attempt}): ${err.message} — retrying`);
            await new Promise((resolve) => setTimeout(resolve, 500 * attempt));
        }
    }
}

/**
 * The manifest, or null when the host serves none. Not fatal: boot falls back to
 * the built-in core list.
 *
 * <p>This replaced a version stamp derived from a HEAD on main_file_cache.dat
 * (Content-Length + Last-Modified — both CORS-safelisted, which is why they were
 * chosen). That stamp could only answer "did anything change?", so it had four
 * failure modes the manifest does not: any change re-downloaded everything; a
 * change confined to an idx file or a slice was invisible; corrupt-but-present
 * bytes were never detected; and if the host omitted either header the stamp was
 * null, which silently disabled persistence and re-downloaded the whole cache on
 * every single visit.
 */
async function loadManifest() {
    try {
        const res = await fetch(CACHE_BASE + MANIFEST_FILE, { cache: "no-store" });
        if (!res.ok) return null;
        const manifest = await res.json();
        if (!manifest || !Array.isArray(manifest.files)) {
            console.warn(`${MANIFEST_FILE} has no files[] — ignoring it`);
            return null;
        }
        return manifest;
    } catch (err) {
        console.warn(`cache manifest unavailable (${err.message})`);
        return null;
    }
}

/** Routes a manifest entry into the cache global the Java side reads it from. */
function publish(entry, bytes) {
    // Int8Array, not Uint8Array: 317 cache bytes are signed and the Java side
    // reads them as a Java byte[].
    const signed = new Int8Array(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    if (entry.path.startsWith(SLICE_PREFIX)) {
        globalThis.__ardorSlices[entry.path.slice(SLICE_PREFIX.length)] = signed;
    } else {
        globalThis.__ardorCache[entry.path] = signed;
    }
}

async function loadCache() {
    globalThis.__ardorCache = globalThis.__ardorCache || {};
    globalThis.__ardorSlices = globalThis.__ardorSlices || {};

    const params = new URLSearchParams(location.search);
    // ?fresh=1 ignores the persisted copy entirely (dev escape hatch).
    // ?verify=1 re-hashes every persisted file instead of trusting the identity
    // it was stored with — the full audit, for when something renders wrong and
    // a corrupt store is a suspect.
    const forceFresh = params.has("fresh");
    const forceVerify = params.has("verify");

    setStatus("Checking cache…");
    const manifest = await loadManifest();
    const entries = manifest ? manifest.files : FALLBACK_FILES;
    if (!manifest) {
        console.warn(
            `no ${MANIFEST_FILE} on the cache host: downloading the 317 cache only. ` +
            `Bundle content (Telos, CoX, Gauntlet) will not render, and files ` +
            `cannot be integrity-checked. Re-run the deploy to publish a manifest.`
        );
    }

    const db = forceFresh ? null : await openDb();
    if (db && manifest) {
        try {
            await pruneUnlisted(db, new Set(entries.map((e) => e.path)));
        } catch (err) {
            console.warn(`cache prune failed: ${err}`);
        }
    }
    // Best-effort: ask the browser not to evict us under storage pressure. A
    // refusal costs a re-download, so it is not worth waiting on the answer.
    if (navigator.storage && navigator.storage.persist) {
        navigator.storage.persist().catch(() => {});
    }

    // Pass 1: what can be served from the store? Cheap — a size + stored-hash
    // identity check per file (or a full rehash under ?verify=1).
    const reused = [];
    const missing = [];
    for (const entry of entries) {
        if (!db) {
            missing.push(entry);
            continue;
        }
        let record = null;
        try {
            record = await idbGet(db, STORE_FILES, entry.path);
        } catch (err) {
            console.warn(`IndexedDB read failed for ${entry.path}: ${err}`);
        }
        if (!recordMatches(record, entry)) {
            missing.push(entry);
            continue;
        }
        if (forceVerify && entry.sha256) {
            const actual = await sha256Hex(record.bytes);
            if (actual && actual !== entry.sha256) {
                console.warn(`?verify: ${entry.path} is corrupt in storage — re-fetching`);
                missing.push(entry);
                continue;
            }
        }
        reused.push({ entry, bytes: record.bytes });
    }

    for (const { entry, bytes } of reused) {
        publish(entry, bytes);
    }

    if (missing.length === 0) {
        const bytes = reused.reduce((n, r) => n + r.bytes.byteLength, 0);
        setStatus(`Cache ready from browser storage (${mb(bytes)} MB). Starting client…`);
        setProgress(null);
        return;
    }

    // Pass 2: download what is missing, with a bar over the KNOWN total. Sizes
    // come from the manifest, so the bar is honest before the first byte lands;
    // without a manifest there is no total and the bar tracks file count.
    const knownTotal = missing.reduce((n, e) => n + (e.size || 0), 0);
    let done = 0;
    let fileIndex = 0;

    for (const entry of missing) {
        fileIndex++;
        const label = `${fileIndex}/${missing.length} ${entry.path}`;
        const describe = () =>
            knownTotal > 0
                ? `Downloading cache: ${mb(done)} / ${mb(knownTotal)} MB — ${label}`
                : `Downloading cache: ${label} (${mb(done)} MB)`;
        setStatus(describe());
        setProgress(knownTotal > 0 ? done / knownTotal : fileIndex / missing.length);

        let lastPaint = 0;
        try {
            const bytes = await fetchCacheFile(entry, (n) => {
                done += n;
                // Repaint at most every 256KB: a per-chunk DOM write on a 42MB
                // file is thousands of layout passes and visibly slower.
                if (done - lastPaint >= 256 * 1024) {
                    lastPaint = done;
                    setStatus(describe());
                    setProgress(knownTotal > 0 ? done / knownTotal : fileIndex / missing.length);
                }
            });

            if (typeof entry.size === "number" && bytes.byteLength !== entry.size) {
                throw new Error(
                    `${entry.path}: got ${bytes.byteLength} bytes, manifest says ${entry.size}`
                );
            }
            const hash = entry.sha256 ? await sha256Hex(bytes) : null;
            if (entry.sha256 && hash && hash !== entry.sha256) {
                throw new Error(`${entry.path}: sha256 mismatch (transfer corrupted)`);
            }

            publish(entry, bytes);
            if (db) {
                // Written per file, immediately: a tab closed mid-download keeps
                // everything already fetched, and the next visit resumes with
                // only the remainder. (The v1 scheme wrote one big transaction at
                // the end, so an interrupted first visit persisted nothing.)
                try {
                    await idbPut(db, STORE_FILES, entry.path, {
                        bytes,
                        size: bytes.byteLength,
                        sha256: hash || entry.sha256 || null,
                    });
                } catch (err) {
                    console.warn(`cache persist failed for ${entry.path}: ${err}`);
                }
            }
        } catch (err) {
            // An optional file is one the client tolerates the absence of: the
            // ephemeral pair, and the slices (no slices = bundle content does not
            // render, which is a degraded game, not a dead page). A required file
            // failing is fatal and reported as such.
            if (entry.optional) {
                console.warn(`optional cache file skipped: ${err.message}`);
                continue;
            }
            throw err;
        }
    }

    setProgress(null);
    setStatus(`Cache loaded (${mb(done)} MB). Starting client…`);
}

async function boot() {
    const canvas = document.getElementById(CANVAS_ID);
    if (!canvas) {
        setStatus(`Missing <canvas id="${CANVAS_ID}">.`, true);
        return;
    }
    canvas.width = FIXED_W;
    canvas.height = FIXED_H;

    let wsUrl;
    try {
        wsUrl = resolveWsUrl();
    } catch (err) {
        setStatus(err.message, true);
        return;
    }

    try {
        await loadCache();
    } catch (err) {
        setProgress(null);
        setStatus(`Failed to load cache: ${err.message}`, true);
        return;
    }

    try {
        const mod = await import("./webclient.js");
        if (typeof mod.start !== "function") {
            throw new Error("./webclient.js does not export start()");
        }
        // Expose the module so a host page / test can call mod.login(user, pass)
        // after boot (the on-screen Login button drives the same path).
        window.__ardor = mod;
        mod.start(CANVAS_ID, wsUrl);
        // Deliberately does NOT name the endpoint. The status line is the one
        // piece of chrome every player sees, and printing the wss:// host there
        // hands out the game server's public address to anyone glancing at the
        // page. It is still discoverable in config.js / devtools — this only
        // removes the casual, zero-effort exposure.
        setStatus("Client started.");

        // Optional autologin from URL params (?user=&pass=) — convenient for dev
        // and headless boot tests; the credentials never leave the local page.
        const qs = new URLSearchParams(location.search);
        const u = qs.get("user");
        const p = qs.get("pass");
        if (u && p && typeof mod.login === "function") {
            setTimeout(() => mod.login(u, p), 1500);
        }
    } catch (err) {
        setStatus(`Failed to start client: ${err.stack || err}`, true);
    }
}

boot();
